FROM mcr.microsoft.com/devcontainers/typescript-node:0-18
RUN apt-get update
# Update to Yarn V3.6.3 from V1
RUN sudo corepack enable && yarn set version berry 

# Yarn V3.6.3
# Node V18.16
# TypeScript V5.1.3